print(1>2) # False # Mayor que
print(1<2) # True # Menor que
print(1<=2) # True # Menor o igual que
print(1>=2) # False # Mayor o igual que
print(1==2) # False # Igual que
print(1!=2) # True # Diferente que
print("a" > "b") # False # Compara por orden alfabetico
print("a" < "b") # True # Compara por orden alfabetico
print("a" == "b") # False # Compara por orden alfabetico
print("a" != "b") # True # Compara por orden alfabetico
print("a" > "A") # True # Compara por orden alfabetico # Las mayusculas son menores que las minusculas
print("a" < "A") # False # Compara por orden alfabetico # Las mayusculas son menores que las minusculas
print("a" == "A") # False # Compara por orden alfabetico # Las mayusculas son menores que las minusculas
print("a" != "A") # True # Compara por orden alfabetico # Las mayusculas son menores que las minusculas
print("abc" > "ab") # True # Compara por orden alfabetico # Compara por orden alfabetico
print("abc" < "ab") # False # Compara por orden alfabetico # Compara por orden alfabetico
print("abc" == "ab") # False # Compara por orden alfabetico # Compara por orden alfabetico
print("abc" != "ab") # True # Compara por orden alfabetico # Compara por orden alfabetico
print(1 == "1") # False # Compara por tipo de dato y valor  # Diferente tipo de dato
print(1 != "1") # True # Compara por tipo de dato y valor  # Diferente tipo de dato
print(1 > "1") # Error # No se puede comparar diferente tipo de dato