numero = [1,2,3]
letras = ["a","b","c"]
palabras = ["chanchito","feliz","comida","alcohol"]
bools = [True,False,False,True,True]
matriz = [[1,0],[2,3]]           #lista de listas
ceros = [0] * 10                 #multiplicar valores de la lista
listadelistas = [[numero],[letras],[palabras],[bools],[matriz],[ceros]] #concatenar listas
alfanumerico = numero + letras   #unir listas
lista_vacia = []                 #vacia pendiente a rellenar
rango = list(range(1,11))        #Crea del 1 al 10
chars = list("hola mundo")       #Separar caractener de un string
letras.remove("a")              # Borra el elemento, si no lo encuentra devuelve FALSE

print(numero)
print(letras)
print(palabras)
print(bools)
print(matriz)
print(ceros)
print(listadelistas)
print(alfanumerico)
print(lista_vacia)
print(rango)
print(chars)








