numero = 2 # entero o integer
decimal = 1.2 # float
imaginario = 1 + 2j # complejo

numero = numero + 2 # reasignacion
numero += 2 # reasignacion acortada suma 2 y se la asigna a numero
numero -= 2 # reasignacion acortada ""
numero *= 2 # reasignacion acortada ""
numero /= 2 # reasignacion acortada ""

print(numero)
print(1+3) #suma
print(3-1) #resta
print(3*2) #multiplicacion
print(3/2) #division
print(3//2) #division entera, sin decimales
print(3**2) #potencia
print(8%2) #modulo, resto de la division

