import math # importa libreria matematica

print(round(3.6)) # redondea al entero mas cercano
print(abs(-77)) # valor absoluto

#MODULO MATH
print(math.ceil(1.1)) # redondea hacia arriba
print(math.floor(1.9)) # redondea hacia abajo
print(math.isnan(23)) # devuelve False si es un numero
#print(math.isnan("23")) # devuelve True si no es un numero
print(math.pow(10,2)) # potencia
print(math.sqrt(25)) # raiz cuadrada
print(math.pi) # numero pi
print(math.e) # numero e

